### ISSUE TITLE
安卓兼容问题

### ISSUE THREAD

**Issue by geekv** [sdc-fe/Framework7-Plus#1]
你好,我下载了你的代码,用gulp dist命令编译生成了dist文件夹,运行里面的index.html,发现了一些在安卓上的兼容问题:
如链接 http://framework7.taobao.org/dist/   ,运行后和官网的这个链接列表页表现是一样的,安卓手机端微信扫一扫打开都有[列表上的箭头图标错位]问题,查看源代码发现是下面的样式在安卓中无效导致的:
.list-block .item-link .item-inner{background-position:calc(100% - 15px)center}
而在你的README.md 描述说:"CSS calc 不支持","已经把他们替换成了 float 或者 absolute 布局",
还有README.md中说"display: flex不支持"的问题也已经解决,但是我在页面仍然能看到display: flex;不支持的相关样式,故心生疑惑,不知道是什么原因,感觉兼容似乎无效.
谢谢(如描述不清楚,可邮件发送源代码).

-----这是后话-----------------------------------------------------------------------------------------------------------------------
反复比对后发现,用gulp build命令生成的build文件夹内的框架代码是修正后的代码,2者是有差异的,恳请作者能将build后的文件一起上传github,或者有个说明方便后来者;
另外,修正后的框架在微信内置浏览器中还是有不少问题的,如"slider无法拖动"等,如果可能,希望作者能兼容下微信内置浏览器,毕竟这个使用场景在目前还是很火的.目前我们团队已经在尝试着去兼容.
最后感谢作者的辛勤付出~

**Comment by lihongxun945** [comment]
你好
感谢你的使用和反馈。

因为作者这个月发布了正式的 1.0 版本，改动较大，我同步之后还没有来得及测试，确实存在一些问题。
箭头错位的问题，你暂时可以通过自己用一个图片背景来实现。
flex 的问题，我现在是替换了主要的组件，比如grid，searchbar，并没有全部换掉，后续会逐渐完善的。如果你发现有问题，可以在自己的样式中覆盖一下，用float布局就好了。

**Comment by lihongxun945** [comment]
关于你的补充。 http://framework7.taobao.org/ 是纯粹的翻译，所以用的依然是原作者的代码。这个不打算修改。

**Comment by geekv** [comment]
刚才发现的,可能gulpfile.js配置有点问题,使用gulp dist编译构建项目产生的dist文件夹内生成的framework7.css和framework7.min.css有差异,正常来说应该只是压缩与否的区别,目前测试发现framework7.css是包含了兼容后的代码样式,包括我前面提到的箭头错位问题,
framework7.min.css则是未修复过的,从而导致打开项目内其他示例demo显示的都是未修复的样子,望知晓~

**Comment by lihongxun945** [comment]
奇怪了，我编译了一下，没有发现问题。min文件是修改过的。

**Comment by lihongxun945** [comment]
还有，可能文档有点歧义，我只是对有问题的 flexbox 做了修改，在lists中的用法是没问题的，所以没有做修改。
