### ISSUE TITLE
可以支持MVVM的其他框架么？

### ISSUE THREAD

**Issue by linuxjcq** [sdc-fe/Framework7-Plus#12]
您好：
      我们公司一直使用的时Knockout.js，请问Framework7支持Knockout.js么？具体要怎么操作

谢谢！

**Comment by lihongxun945** [comment]
@linuxjcq  这个我也没用过，不好说到底可以不可以。
如果只是MVVM的话，我认为是不会存在太大问题的。F7 重点在 路由 和 组件，而knockout是实现model 和view渲染。也就是说f7管理页面加载/切换和组件，knockout 负责渲染页面的内容，但是渲染出来的很多依然是F7的组件。
一个负责UI，一个负责数据和渲染，应该可以配合使用的。

**Comment by lihongxun945** [comment]
@linuxjcq  你可以尝试下，页面的结构，page切换，组件使用 F7，而从服务器取数据，渲染页面内容，数据绑定和用户操作用 knockout。
