### ISSUE TITLE
编译后的 Cards、Picker、Calendar / Datepicker、Swiper Slider 无论IOS和Android显示有问题

### ISSUE THREAD

**Issue by feifei8** [sdc-fe/Framework7-Plus#2]
首先感谢作者的辛苦！

在使用作者提供的源码进行gulp build编译后，发现 Cards、Picker、Calendar / Datepicker、Swiper Slider 无论IOS和Android显示都有问题，由于是菜鸟，不能定位问题，但感觉可滚动条有关，还望楼主给予修正，谢谢！

**Comment by lihongxun945** [comment]
感谢反馈，你说的这几个组件都是1.0.0新增的，（swiper也是新的），我更新之后还没来得及测试，这周末我会测试这几个组件

**Comment by feifei8** [comment]
感谢楼主

**Comment by BelinChung** [comment]
@lihongxun945 持续保持对该项目的关注
请问现在 framework7.taobao.org 目前在阿里属于哪个团队负责？团队业余还是团队任务？

**Comment by lihongxun945** [comment]
@BelinChung  这个现在是我个人用业余时间做的，跟公司没关系的

**Comment by lihongxun945** [comment]
@feifei8  ，你说的几个组件，除了 slider 高度不对的问题之外，我没有发现其他组件在ios上有问题。

**Comment by feifei8** [comment]
是的，IOS 上Swiper Slider 原来的高度的问题，其他的都是Android上的问题，我下载了最新的代码编译，IOS上的问题一切OK。感谢作者的辛苦劳动与分享

**Comment by lihongxun945** [comment]
@feifei8  安卓上有哪些 问题，可以详细列出来吗，我会逐个修复的。周末我用三星 s3 和 华为的一款手机测试了 一下，没有发现问题。

**Comment by feifei8** [comment]
picker 是最下面的选择项不能完整显示，拖动滚动条上拉 也显示不出，好像是滚动条的原因，另外选择时效率有很大问题。
3D cube 3D Converflow Effect 也是高度的问题，仅显示一点
message 不能显示出提问人的信息，仅显示电脑的信息

以上错误 是在Android红米上测试出现的。本现上传图片，但不知怎么传

**Comment by lihongxun945** [comment]
@feifei8  好的。不能完整显示， 确实是滚动条的问题。我这周会再更新的。

**Comment by feifei8** [comment]
还发现一个滚动条的问题，在Andriod系统下，在滑动内容时，看不到滚动条的位置，有的机型，一直停留在上部，就是滚动条不随内容滚l动而动

**Comment by lihongxun945** [comment]
@feifei8  安卓系统就是不显示滚动条的。降级到js滚动条时，是可以显示的，但是为了性能考虑 也没有显示出来，因为降级的系统肯定都是性能不好的手机。
那个滚动条停留在顶部，我没发现，具体是什么手机什么系统版本？

**Comment by lihongxun945** [comment]
@feifei8  这个issue太宽泛了，我关掉了，你可以再把具体的问题提出来，一个issue只包含一个问题。

**Comment by feifei8** [comment]
好的
