### ISSUE TITLE
Models 没有遮罩

### ISSUE THREAD

**Issue by yucopowo** [sdc-fe/Framework7-Plus#3]
![cb6b6c5c-09d4-4506-90b8-bfe9e25b0c87](https://cloud.githubusercontent.com/assets/4240629/6506260/99fbb770-c384-11e4-98f2-932e548c88f9.png)
1.没有遮罩
2.confirm自动触发ok键

**Comment by lihongxun945** [comment]
已修复，感谢反馈。

**Comment by lihongxun945** [comment]
@yucopowo  你可以clone 最新代码试一下
