### ISSUE TITLE
Swiper Slider里面的Custom Controls在任何设备都显示不出来

### ISSUE THREAD

**Issue by geekv** [sdc-fe/Framework7-Plus#5]
这是一个相册的效果,该效果页面位于kitchen-sink目录下的swiper-gallery.html文件,如果我把框架原作者的framework7的framework7.js替换过来,就一切显示正常;

**Comment by lihongxun945** [comment]
@geekv  我看了下，还是滚动条的问题，因为滚动条新加了一个 'page-content-inner' 导致slider容器高度不对了。这个我会改的。你可以设置下高度就好了。

**Comment by geekv** [comment]
是的  加了后就解决了  这个后期你改的思路是?

**Comment by lihongxun945** [comment]
其实只是这个demo中设置下高度就行了。我改下css就行了

**Comment by lihongxun945** [comment]
这个就是demo中页面高度的问题，我已经修复了。并且更新了 1.0.3 版本。
