### ISSUE TITLE
建议替换 iScroll.js

### ISSUE THREAD

**Issue by evolutionjay** [sdc-fe/Framework7-Plus#7]
建议把 iScroll 替换成 http://greensock.com/draggable

我研究过，这东西的效率很高，它内容滚动的时候是用原生的滚动，
只有在边缘的时候才触发 css3 transform 属性。

**Comment by lihongxun945** [comment]
@evolutionjay  你可能理解错了。JS 滚动条不是为了解决性能问题，而是在低版本的安卓上，原生滚动是有bug的，会导致绝对定位的元素闪动，所以必须换成JS滚动条，性能是会降低的，但是不会闪动。

**Comment by evolutionjay** [comment]
恩，明白了，不过我觉得还是不妥，毕竟我从 iScroll4 一路走过来，做了很多个iScroll的项目，深知这东西在国内环境下的弊端。以前帮联想做了一个安卓端的webapp，用iScroll在他们的4.3机器上，直接把界面卡成狗。

**Comment by lihongxun945** [comment]
@evolutionjay  我也发现了这个问题，IScroll 我改了一点代码，目前没发现问题。不知道有没有更好的JS滚动条

**Comment by evolutionjay** [comment]
目前iScroll是最好的js滚动条。
