### ISSUE TITLE
官方更新后，Framework7-Plus需要怎么做修改跟进呢

### ISSUE THREAD

**Issue by binarx** [sdc-fe/Framework7-Plus#8]
比如说，官方更新了1.0.4，我用的是plus版本，如果想要更新，有办法吗？

**Comment by lihongxun945** [comment]
���û�а취����һ���ÿ�ܸ��£���ٻ����ͬ����ȵġ�
��Ϊ��һЩ�����ϵ��޸���Ҫmerge��
1.0.4 �Ĵ��룬�һ��ڱ�����ĩ�㶨��

**Comment by binarx** [comment]
知晓，谢谢
